### ISSUE TITLE
Seção Como ter o JS4Girls na sua Cidade

### ISSUE THREAD

**Issue by suissa** [Webschool-io/js4girls-site#18]
Seção Como ter o JS4Girls na sua Cidade

**Comment by vineckb** [comment]
Ta ai, para validação.

A principio, acho que só essa imagem de fundo que deveria ser trocada, mas vou ficar devendo isso. Mesmo se eu manjasse dos paranaue, não rolaria pq to sem PS.

**Comment by henricavalcante** [comment]
Ajusta os conflitos para eu fazer merge.
