### ISSUE TITLE
Site Offline

### ISSUE THREAD

**Issue by adammacias** [Webschool-io/js4girls-site#7]
O domínio [http://js4girls.com/](js4girls.com) aqui offline, o [gh-pages](http://webschool-io.github.io/js4girls-site/) esta normal. É só aqui?

**Comment by henricavalcante** [comment]
Webschool-io.github.io/js4girls-site

**Comment by henricavalcante** [comment]
@suissa  como estão as configurações de DNS do domínio? tem que criar A recorda para 192.30.252.153 e 192.30.252.154
